# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cdn.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cdn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcdn.proto\x12\x03\x63\x64n\"6\n\x11\x46ileDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0bhard_delete\x18\x02 \x01(\x08\"6\n\x12\x46ileDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07is_done\x18\x02 \x01(\x08\"j\n\x10SetToPathRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x04 \x01(\t\x12\x12\n\nmodel_name\x18\x05 \x01(\t\"j\n\x11SetToPathResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\x12\x10\n\x08\x65rr_text\x18\x02 \x01(\t\x12\x0f\n\x07new_url\x18\x03 \x01(\t\x12\x10\n\x08new_uuid\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x83\x01\n\x14\x46ileMetadataResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x03\"+\n\x13\x46ileContentResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"*\n\x12\x46ileStatusResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x32\xc3\x02\n\nCDNService\x12>\n\x0fGetFileMetadata\x12\x10.cdn.FileRequest\x1a\x19.cdn.FileMetadataResponse\x12>\n\x0eGetFileContent\x12\x10.cdn.FileRequest\x1a\x18.cdn.FileContentResponse0\x01\x12:\n\tSetToPath\x12\x15.cdn.SetToPathRequest\x1a\x16.cdn.SetToPathResponse\x12:\n\rGetFileStatus\x12\x10.cdn.FileRequest\x1a\x17.cdn.FileStatusResponse\x12=\n\nDeleteFile\x12\x16.cdn.FileDeleteRequest\x1a\x17.cdn.FileDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cdn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEDELETEREQUEST']._serialized_start=18
  _globals['_FILEDELETEREQUEST']._serialized_end=72
  _globals['_FILEDELETERESPONSE']._serialized_start=74
  _globals['_FILEDELETERESPONSE']._serialized_end=128
  _globals['_SETTOPATHREQUEST']._serialized_start=130
  _globals['_SETTOPATHREQUEST']._serialized_end=236
  _globals['_SETTOPATHRESPONSE']._serialized_start=238
  _globals['_SETTOPATHRESPONSE']._serialized_end=344
  _globals['_FILEREQUEST']._serialized_start=346
  _globals['_FILEREQUEST']._serialized_end=373
  _globals['_FILEMETADATARESPONSE']._serialized_start=376
  _globals['_FILEMETADATARESPONSE']._serialized_end=507
  _globals['_FILECONTENTRESPONSE']._serialized_start=509
  _globals['_FILECONTENTRESPONSE']._serialized_end=552
  _globals['_FILESTATUSRESPONSE']._serialized_start=554
  _globals['_FILESTATUSRESPONSE']._serialized_end=596
  _globals['_CDNSERVICE']._serialized_start=599
  _globals['_CDNSERVICE']._serialized_end=922
# @@protoc_insertion_point(module_scope)
