# Generated by Django 5.1.4 on 2025-01-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.FloatField(default=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('version', models.CharField(default=True, max_length=64, null=True)),
                ('path', models.URLField(default=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cdn_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
