# Generated by Django 5.1.4 on 2025-01-15 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
