# Generated by Django 5.1.4 on 2025-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_remove_file_path_file_created_at_file_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
