# Generated by Django 5.1.4 on 2025-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0004_file_content_type_file_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_temp_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
