# Generated by Django 5.1.4 on 2025-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0005_file_last_temp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
