# Generated by Django 5.0.4 on 2025-01-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0006_alter_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_temp_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
